---
- name: Install vim (text)
  apt: pkg=vim install_recommends=False state=present

- name: Install gVim
  apt: pkg=vim-gtk install_recommends=False state=present
  when: vim_install_gvim

- name: Install helper tools
  apt:  pkg={{ item }} install_recommends=False state=present 
  with_items:
    - grep 
    - silversearcher-ag
    - exuberant-ctags
  when: vim_install_tools

- name: update user configuration
  copy: src=user.vim/ dest=~/.vim


#- name: set vim as default editor
#  alternatives: "link={{ item }} target=/usr/bin/vim.basic"
#  with_items: [editor, ex, rview, rvim, vi, view, vim, vimdiff]
    
