---
- name: Setup workstation
  hosts: workstation 
  gather_facts: false
  roles:
      - common
      - vim-install
      - ansible-role-virtualbox

- name: Setup server
  hosts: server 
  gather_facts: false
  roles:
      - ansible_client_bootstrap
